[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = true

# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Duration (in seconds) of the user session expiry
user_session_timeout = 1296000  # 15 days

# Enable third parties caching (e.g LangChain cache)
cache = false

# Authorized origins
allow_origins = ["*"]

[server]
# Server host and port
host = "0.0.0.0"
port = 8000

# Enable WebSocket support
use_websockets = true
# Enable Socket.IO support
socketio_enabled = true
socketio_cors_allowed_origins = ["*"]


# Add explicit CORS configuration
[server.cors]
allow_origins = ["*"]
allow_methods = ["*"]
allow_headers = ["*"]

[features]
# Process and display HTML in messages
unsafe_allow_html = false

# Process and display mathematical expressions
latex = false

# Autoscroll new user messages at the top of the window
user_message_autoscroll = true

# Automatically tag threads with the current chat profile (if a chat profile is used)
auto_tag_thread = true

# Allow users to edit their own messages
edit_message = true

# Authorize users to spontaneously upload files with messages
[features.spontaneous_file_upload]
    enabled = true
    accept = ["*/*"]
    max_files = 20
    max_size_mb = 500

[features.audio]
# Sample rate of the audio
sample_rate = 24000

[UI]
# Name of the assistant
name = "GenAI System"

# Chain of Thought (CoT) display mode
cot = "full"

# Specify a CSS file that can be used to customize the user interface
custom_css = "/public/app.css"

[meta]
generated_by = "2.4.1"
